# Generated by Django 6.0.1 on 2026-04-04 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('client_address', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('website', 'Website Development'), ('ecommerce', 'E-Commerce Website'), ('seo', 'SEO Optimization'), ('redesign', 'Website Redesign'), ('landing', 'Landing Page'), ('maintenance', 'Website Maintenance'), ('custom', 'Custom Project')], max_length=20)),
                ('project_title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_percent', models.PositiveIntegerField(default=50, help_text='Advance payment %')),
                ('payment_terms', models.TextField(blank=True)),
                ('additional_terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('signed', 'Signed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_signed', models.BooleanField(default=False)),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('weblance_signed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
