# Generated by Django 6.0.1 on 2026-04-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='project_type',
            field=models.CharField(choices=[('website', 'Website Development'), ('ecommerce', 'E-Commerce Website'), ('seo', 'SEO Optimization'), ('redesign', 'Website Redesign'), ('landing', 'Landing Page'), ('maintenance', 'Website Maintenance'), ('portfolio', 'Portfolio Website'), ('blog', 'Blog / News Website'), ('education', 'School / Education Website'), ('restaurant', 'Restaurant Website'), ('realestate', 'Real Estate Website'), ('hospital', 'Hospital / Clinic Website'), ('webapp', 'Web Application Development'), ('custom', 'Custom Project')], max_length=20),
        ),
    ]
