# Generated by Django 6.0.1 on 2026-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website_type', models.CharField(choices=[('business', 'Business Website'), ('ecommerce', 'E-Commerce Website'), ('landing', 'Landing Page'), ('custom', 'Custom Website')], max_length=20)),
                ('budget', models.CharField(choices=[('low', 'Below ₹10,000'), ('medium', '₹10,000 - ₹25,000'), ('high', '₹25,000 - ₹50,000'), ('premium', 'Above ₹50,000')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
