# Generated by Django 6.0.1 on 2026-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsite', '0002_websiterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='selected_plan',
            field=models.CharField(blank=True, default='', help_text='Pricing plan selected by client', max_length=100),
        ),
    ]
