# Generated by Django 6.0.1 on 2026-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsite', '0003_websiterequest_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='proposal',
            field=models.TextField(blank=True, default='', help_text='Auto-generated website proposal JSON'),
        ),
    ]
