# Generated by Django 6.0.1 on 2026-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsite', '0004_add_proposal_to_websiterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='selected_template',
            field=models.CharField(blank=True, default='', help_text='Template selected by client from proposal', max_length=200),
        ),
    ]
