# Generated by Django 6.0.1 on 2026-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsite', '0006_websiterequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', help_text='Reason provided by client when cancelling'),
        ),
    ]
