# Generated by Django 6.0.1 on 2026-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsite', '0007_websiterequest_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
