# Generated by Django 5.0.6 on 2026-08-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsite', '0008_alter_websiterequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='website_type',
            field=models.CharField(choices=[('website', 'Website Development'), ('ecommerce', 'E-Commerce Website'), ('seo', 'SEO Optimization'), ('redesign', 'Website Redesign'), ('landing', 'Landing Page'), ('maintenance', 'Website Maintenance'), ('portfolio', 'Portfolio Website'), ('blog', 'Blog / News Website'), ('education', 'School / Education Website'), ('restaurant', 'Restaurant Website'), ('realestate', 'Real Estate Website'), ('hospital', 'Hospital / Clinic Website'), ('webapp', 'Web Application Development'), ('college', 'College Project'), ('academic', 'Academic Project'), ('miniproject', 'Mini Project'), ('custom', 'Custom Project')], max_length=20),
        ),
    ]
