# Generated by Django 6.0.1 on 2026-04-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Pricing plan booked for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pricing.pricingplan'),
        ),
    ]
