# Generated by Django 6.0.1 on 2026-04-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_plan_to_clientproject'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pricing.pricingplan'),
        ),
    ]
