# Generated by Django 5.0.6 on 2026-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Summer Special – 20% OFF', max_length=200)),
                ('description', models.TextField(help_text='Short description shown on the offer card.')),
                ('badge_text', models.CharField(blank=True, help_text='Small badge label, e.g. "Limited Time"', max_length=60)),
                ('badge_color', models.CharField(choices=[('saffron', '🟠 Saffron'), ('green', '🟢 Green'), ('indigo', '🟣 Indigo'), ('red', '🔴 Red'), ('gold', '🟡 Gold')], default='indigo', max_length=20)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, help_text='Optional numeric discount %, e.g. 20 → shows "20% OFF"', null=True)),
                ('cta_label', models.CharField(default='Claim Offer', help_text='Button text', max_length=80)),
                ('cta_url', models.CharField(default='/request-website/', help_text='Button link', max_length=300)),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active offers are shown on the website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
