# Generated by Django 5.0.6 on 2026-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_offer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='service_type',
            field=models.CharField(blank=True, choices=[('', 'Any Service (General Offer)'), ('business', 'Business Website'), ('ecommerce', 'E-Commerce Website'), ('landing', 'Landing Page'), ('custom', 'Custom Website')], default='', help_text='Which service this offer applies to. Leave blank = any service.', max_length=20),
        ),
    ]
