# Generated by Django 6.0.1 on 2026-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('business', 'Business Websites'), ('ecommerce', 'E-Commerce Websites'), ('landing', 'Landing Pages')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/%d/')),
                ('live_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
