# Generated by Django 5.0.6 on 2026-08-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste a direct image URL (Cloudinary, Imgur, etc.)', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('business', 'Business Websites'), ('ecommerce', 'E-Commerce Websites'), ('landing', 'Landing Pages'), ('seo', 'SEO Optimization'), ('redesign', 'Website Redesign'), ('maintenance', 'Website Maintenance'), ('portfolio', 'Portfolio Websites'), ('blog', 'Blog / News Websites'), ('education', 'School / Education Websites'), ('restaurant', 'Restaurant Websites'), ('realestate', 'Real Estate Websites'), ('hospital', 'Hospital / Clinic Websites'), ('webapp', 'Web Applications'), ('college', 'College Projects'), ('academic', 'Academic Projects'), ('miniproject', 'Mini Projects'), ('custom', 'Custom Projects')], max_length=20),
        ),
    ]
