# Generated by Django 6.0.1 on 2026-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason provided by client when cancelling'),
        ),
    ]
